#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 4.25.1
#  in conjunction with Tcl version 8.6
#    Dec 26, 2019 01:11:00 PM PKT  platform: Windows NT

import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import admiin_support
import main
import lgin

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = tk.Tk()
    root.state("zoomed")
    top = Toplevel1 (root)
    admiin_support.init(root, top)
    root.mainloop()

w = None
def create_Toplevel1(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = tk.Toplevel (root)
    top = Toplevel1 (w)
    admiin_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_Toplevel1():
    global w
    w.destroy()
    w = None

class Toplevel1:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#ececec' # Closest X11 color: 'gray92'
        font10 = "-family {Segoe UI} -size 14 -weight bold -slant "  \
            "roman -underline 0 -overstrike 0"
        font11 = "-family {Segoe UI} -size 14 -weight normal -slant "  \
            "roman -underline 0 -overstrike 0"
        font9 = "-family {Segoe UI} -size 30 -weight bold -slant roman"  \
            " -underline 0 -overstrike 0"

        top.geometry("2066x1263+650+150")
        top.title("Sketch Matcher")
        top.configure(background="#e3faf9")
        file="cred.txt"
        uss=""
        with open(file) as fp:
#            line=fp.readline()
#            line2=fp.readline()
            for line in fp:
                line2=next(fp)
                line3=next(fp)
#            while line2 and line:
                us=line.strip()
                pww=line2.strip()
                cn=line3.strip()
                uss=uss+"User: "+us+"\t Password: "+pww+"\t CNIC: "+cn+"\n"
        

        self.Button1 = tk.Button(top)
        self.Button1.place(relx=0.69, rely=0.728, height=54, width=162)
        self.Button1.configure(activebackground="#ececec")
        self.Button1.configure(activeforeground="#000000")
        self.Button1.configure(background="#ffffff")
        self.Button1.configure(disabledforeground="#a3a3a3")
        self.Button1.configure(font=font11)
        self.Button1.configure(foreground="#000000")
        self.Button1.configure(highlightbackground="#d9d9d9")
        self.Button1.configure(highlightcolor="black")
        self.Button1.configure(pady="0")
        self.Button1.configure(text='''Matcher''')
        self.Button1.configure(command=matcher)

        self.Button1_1 = tk.Button(top)
        self.Button1_1.place(relx=0.69, rely=0.823, height=54, width=162)
        self.Button1_1.configure(activebackground="#ececec")
        self.Button1_1.configure(activeforeground="#000000")
        self.Button1_1.configure(background="#FFFFFF")
        self.Button1_1.configure(disabledforeground="#a3a3a3")
        self.Button1_1.configure(font=font11)
        self.Button1_1.configure(foreground="#000000")
        self.Button1_1.configure(highlightbackground="#d9d9d9")
        self.Button1_1.configure(highlightcolor="black")
        self.Button1_1.configure(pady="0")
        self.Button1_1.configure(text='''Logout''')
        self.Button1_1.configure(command=backk)

        self.Text1 = tk.Text(top)
        self.Text1.place(relx=0.227, rely=0.166, relheight=0.508, relwidth=0.549)

        self.Text1.configure(background="white")
        self.Text1.configure(font="TkTextFont")
        self.Text1.configure(foreground="black")
        self.Text1.configure(highlightbackground="#FFFFFF")
        self.Text1.configure(highlightcolor="black")
        self.Text1.configure(insertbackground="black")
        self.Text1.configure(selectbackground="#c4c4c4")
        self.Text1.configure(selectforeground="black")
        self.Text1.configure(wrap="word")
        self.Text1.insert("1.0",uss)

        self.Label1 = tk.Label(top)
        self.Label1.place(relx=0.227, rely=0.110, height=56, width=110)
        self.Label1.configure(background="#e3faf9")
        self.Label1.configure(disabledforeground="#a3a3a3")
        self.Label1.configure(font=font10)
        self.Label1.configure(foreground="#000000")
        self.Label1.configure(text='''Users:''')

        self.Label2 = tk.Label(top)
        self.Label2.place(relx=0.261, rely=0.016, height=98, width=1002)
        self.Label2.configure(background="#e3faf9")
        self.Label2.configure(disabledforeground="#a3a3a3")
        self.Label2.configure(font=font9)
        self.Label2.configure(foreground="#000000")
        self.Label2.configure(text='''Sketch Matcher''')
def backk():
    global root
    root.destroy()
    lgin.vp_start_gui()
def matcher():
    global root
    root.destroy()
    main.vp_start_gui()
if __name__ == '__main__':
    vp_start_gui()





