#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 4.25.1
#  in conjunction with Tcl version 8.6
#    Dec 26, 2019 12:35:48 PM PKT  platform: Windows NT

import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    from tkinter import messagebox
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    from tkinter import messagebox
    py3 = True
import lgin
import forgot_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = tk.Tk()
    root.state("zoomed")
    top = Toplevel1 (root)
    forgot_support.init(root, top)
    root.mainloop()

w = None
def create_Toplevel1(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = tk.Toplevel (root)
    top = Toplevel1 (w)
    forgot_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_Toplevel1():
    global w
    w.destroy()
    w = None

class Toplevel1:
    def recv(self):
        ch=0
        file="cred.txt"
        cnic=self.Entry1.get()
        self.Entry1.delete(0,'end')
        with open(file) as fp:
    #            line=fp.readline()
    #            line2=fp.readline()
            for line in fp:
                line2=next(fp)
                line3=next(fp)
    #            while line2 and line:
                us=line.strip()
                pww=line2.strip()
                cn=line3.strip()
                ch=-1
                if cnic==cn:
                    ch=1
                    messagebox.showinfo("Recover Successful!","Your Password is: "+pww)

                    
    #                    root.withdraw()
    #                    main.vp_start_gui()
                    break
        if ch==-1:
            messagebox.showinfo("Recover Failed!","Contact Admin.",icon="warning")
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#ececec' # Closest X11 color: 'gray92'
        font11 = "-family {Segoe UI} -size 30 -weight bold -slant "  \
            "roman -underline 0 -overstrike 0"

        top.geometry("2179x1446+650+150")
        top.title("Sketch Matcher")
        top.configure(background="#e3faf9")

        self.Label1 = tk.Label(top)
        self.Label1.place(relx=0.303, rely=0.166, height=338, width=782)
        self.Label1.configure(background="#e3faf9")
        self.Label1.configure(disabledforeground="#a3a3a3")
        self.Label1.configure(font=font11)
        self.Label1.configure(foreground="#000000")
        self.Label1.configure(text='''Password Recovery''')

        self.Entry1 = tk.Entry(top)
        self.Entry1.place(relx=0.450, rely=0.533,height=44, relwidth=0.258)
        self.Entry1.configure(background="white")
        self.Entry1.configure(disabledforeground="#a3a3a3")
        self.Entry1.configure(font="TkFixedFont")
        self.Entry1.configure(foreground="#000000")
        self.Entry1.configure(insertbackground="black")

        self.Label2 = tk.Label(top)
        self.Label2.place(relx=0.303, rely=0.533, height=44, width=242)
        self.Label2.configure(background="#e3faf9")
        self.Label2.configure(font=("Courier -bold", 20))
        self.Label2.configure(disabledforeground="#a3a3a3")
        self.Label2.configure(foreground="#000000")
        self.Label2.configure(text='''Enter CNIC:''')

        self.Button1 = tk.Button(top)
        self.Button1.place(relx=0.623, rely=0.643, height=54, width=162)
        self.Button1.configure(activebackground="#ececec")
        self.Button1.configure(activeforeground="#000000")
        self.Button1.configure(background="#ffffff")
        self.Button1.configure(disabledforeground="#a3a3a3")
        self.Button1.configure(font=("Courier", 15))
        self.Button1.configure(foreground="#000000")
        self.Button1.configure(highlightbackground="#d9d9d9")
        self.Button1.configure(highlightcolor="black")
        self.Button1.configure(pady="0")
        self.Button1.configure(text='''Recover''')
        self.Button1.configure(command=self.recv)
        
        self.back = tk.Button(top)
        self.back.place(relx=0.623, rely=0.743, height=54, width=162)
        self.back.configure(activebackground="#ececec")
        self.back.configure(activeforeground="#000000")
        self.back.configure(background="#ffffff")
        self.back.configure(disabledforeground="#a3a3a3")
        self.back.configure(font=("Courier", 15))
        self.back.configure(foreground="#000000")
        self.back.configure(highlightbackground="#d9d9d9")
        self.back.configure(highlightcolor="black")
        self.back.configure(pady="0")
        self.back.configure(text='''Back''')
        self.back.configure(command=bakk)
        
def bakk():
    global root
    root.destroy()
    lgin.vp_start_gui()
if __name__ == '__main__':
    vp_start_gui()





