#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 4.25.1
#  in conjunction with Tcl version 8.6
#    Oct 23, 2019 09:44:50 PM PKT  platform: Windows NT

import sys
import first
import t1
import main
import forgot
import admiin
try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import lgin_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root,im
    root = tk.Tk()
    root.state("zoomed")
    top = Toplevel1 (root)
    lgin_support.init(root, top)
    root.mainloop()

w = None
def create_Toplevel1(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = tk.Toplevel (root)
    top = Toplevel1 (w)
    lgin_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_Toplevel1():
    global w
    w.destroy()
    w = None

class Toplevel1:
    def back(self):
        root.withdraw()
        first.vp_start_gui()
    def login(self):
        ch=0
        file="cred.txt"
        user=self.ident.get()
        pw=self.pwent.get()
        self.ident.delete(0,'end')
        self.pwent.delete(0,'end')
        with open(file) as fp:
#            line=fp.readline()
#            line2=fp.readline()
            for line in fp:
                line2=next(fp)
                line3=next(fp)
#            while line2 and line:
                us=line.strip()
                pww=line2.strip()
                cn=line3.strip()
                ch=-1
                if user=="admin" and pw=="admin":
                    ch=1
                    fileuser="cuser.txt"
                    fileus=open(fileuser,"w")
                    fileus.write(user+"\n")
                    fileus.close()
                    adminn()
                elif us==user and pw==pww:
                    ch=1
                    self.Label1.configure(text="login Successful!")
                    fileuser="cuser.txt"
                    fileus=open(fileuser,"w")
                    fileus.write(user+"\n")
                    fileus.close()
#                    root.withdraw()
#                    main.vp_start_gui()
                    loginn()
                    
                    break
        if ch==-1:
            self.Label1.configure(text="User Not Found.")
            
        
            
        
        
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#ececec' # Closest X11 color: 'gray92'
        font9 = "-family {Segoe UI} -size 36 -weight bold -slant roman"  \
            " -underline 0 -overstrike 0"

        top.geometry("1742x1203+650+150")
        top.title("Sketch Matcher")
        top.configure(background="#e3faf9")

        self.Label1 = tk.Label(top)
        self.Label1.place(relx=0.23, rely=0.216, height=208, width=1002)####
        self.Label1.configure(background="#e3faf9")
        self.Label1.configure(disabledforeground="#a3a3a3")
        self.Label1.configure(font=font9)
        self.Label1.configure(foreground="#000000")
        self.Label1.configure(text='''Login''')

        self.ident = tk.Entry(top)
        self.ident.place(relx=0.448, rely=0.482,height=34, relwidth=0.186)
        self.ident.configure(background="white")
        self.ident.configure(disabledforeground="#a3a3a3")
        self.ident.configure(font="TkFixedFont")
        self.ident.configure(foreground="#000000")
        self.ident.configure(insertbackground="black")

        self.pwent = tk.Entry(top)
        self.pwent.place(relx=0.448, rely=0.549,height=34, relwidth=0.186)
        self.pwent.configure(background="white")
        self.pwent.configure(disabledforeground="#a3a3a3")
        self.pwent.configure(font="TkFixedFont")
        self.pwent.configure(foreground="#000000")
        self.pwent.configure(insertbackground="black")

        self.Label2 = tk.Label(top)
        self.Label2.place(relx=0.321, rely=0.482, height=38, width=140) ###########
        self.Label2.configure(background="#e3faf9")########################
        self.Label2.configure(disabledforeground="#a3a3a3")
        self.Label2.configure(foreground="#000000")
        self.Label2.configure(font=("Courier", 20))############################
        self.Label2.configure(text='''Username:''')

        self.Label3 = tk.Label(top)
        self.Label3.place(relx=0.321, rely=0.549, height=40, width=140)########################
        self.Label3.configure(background="#e3faf9")########################
        self.Label3.configure(disabledforeground="#a3a3a3")
        self.Label3.configure(foreground="#000000")
        self.Label3.configure(font=("Courier", 20))########################
        self.Label3.configure(text='''Password:''')
        
        
        self.forgt = tk.Button(top)
        self.forgt.place(relx=0.545, rely=0.600, height=40, width=190)########################
        self.forgt.configure(background="#e3faf9")########################
        self.forgt.configure(disabledforeground="#3b5998")
        self.forgt.configure(activebackground="#e3faf9")
        self.forgt.configure(foreground="#000000")
        self.forgt.configure(bd=0)
        self.forgt.configure(font=("Courier", 14))########################
        self.forgt.configure(text='''Forgot Password?''')
        self.forgt.configure(command=frgt)
        

        self.loginbtn = tk.Button(top)
        self.loginbtn.place(relx=0.55, rely=0.643, height=54, width=162)########
        self.loginbtn.configure(activebackground="#ececec")
        self.loginbtn.configure(activeforeground="#000000")
        self.loginbtn.configure(background="#FFFFFF")
        self.loginbtn.configure(disabledforeground="#a3a3a3")
        self.loginbtn.configure(foreground="#000000")
        self.loginbtn.configure(highlightbackground="#d9d9d9")
        self.loginbtn.configure(highlightcolor="black")
        self.loginbtn.configure(pady="0")
        self.loginbtn.configure(font=("Courier", 14))#########
        self.loginbtn.configure(text='''Login''')
        self.loginbtn.configure(command=self.login)
        
        self.bckbtn = tk.Button(top)
        self.bckbtn.place(relx=0.55, rely=0.73, height=54, width=162)######
        self.bckbtn.configure(activebackground="#ececec")
        self.bckbtn.configure(activeforeground="#000000")
        self.bckbtn.configure(background="#FFFFFF") ######
        self.bckbtn.configure(disabledforeground="#a3a3a3")
        self.bckbtn.configure(foreground="#000000")
        self.bckbtn.configure(highlightbackground="#d9d9d9")
        self.bckbtn.configure(highlightcolor="black")
        self.bckbtn.configure(pady="0")
        self.bckbtn.configure(font=("Courier", 14))#########
        self.bckbtn.configure(text='''Back''')
        self.bckbtn.configure(command=backk)
def adminn():
    global root
    root.destroy()
    admiin.vp_start_gui()
def backk():
    global root
    root.destroy()
    first.vp_start_gui()
def frgt():
    global root
    root.destroy()
    forgot.vp_start_gui()
def loginn():
    global root
    root.destroy()
    main.vp_start_gui()
if __name__ == '__main__':
    vp_start_gui()





